---
language: python
python: "2.7"

sudo: required
dist: trusty
group: deprecated-2017Q2

addons:
  apt:
    sources:
    - sourceline: ppa:ansible/ansible
    packages:
    - ansible

before_install:
- ansible --version
- cd tests

install:
- ansible-galaxy install -r roles.yml

script:
- ansible-playbook -i localhost test.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
