---
# tasks file for gvm
# https://github.com/moovweb/gvm/blob/master/binscripts/gvm-installer
- name: Create directories
  file:
    dest: "{{ gvm_root | dirname }}"
    state: directory
- name: Clone gvm
  git:
    repo: "{{ gvm_repo }}"
    dest: "{{ gvm_root }}"
    version: "{{ gvm_version }}"
    update: "{{ gvm_update }}"
- block:
  - name: Add configurations to ~/.bashrc, ~/.profile, or ~/.zshrc or etc
    lineinfile:
      dest: "{{ gvm_rc_path }}"
      line: '[[ -s "{{ gvm_root }}/scripts/gvm" ]] && source "{{ gvm_root }}/scripts/gvm"'
      regexp: '^\[\[ -s ".*/scripts/gvm" \]\] && source ".*/scripts/gvm"$'
      create: yes
  - name: Add configurations to $GVM_ROOT/scripts/gvm
    lineinfile:
      dest: "{{ gvm_root }}/scripts/gvm"
      line: 'export GVM_ROOT="{{ gvm_root }}"'
      regexp: '^export GVM_ROOT='
      create: yes
  - name: Add configurations to $GVM_ROOT/scripts/gvm
    lineinfile:
      dest: "{{ gvm_root }}/scripts/gvm"
      line: '. $GVM_ROOT/scripts/gvm-default'
      create: yes
  when: gvm_rc_path != "NOT ADD"
# https://github.com/moovweb/gvm/blob/master/scripts/gvm-default
- name: create directories (gvm-default)
  file:
    name: "{{ gvm_root }}/{{ item }}"
    state: directory
  items:
  - logs
  - gos
  - archive/packages
  - environments
- block:
  - name: create directories
    file:
      name: "{{ gvm_root }}/{{ item }}"
      state: directory
    items:
    - environments
    - pkgsets/system/global
    - gos/system
  - name: create $GVM_ROOT/environments/system
    template:
      src: system
      dest: "{{ gvm_root }}/environments/system"
  when: gvm_goroot is not undefined
- include: "{{ gvm_os_families.get(ansible_os_family, 'default') }}.yml"
  static: no
  when: gvm_is_dependencies_installed and ansible_os_family in gvm_os_families
