---
# tasks file for gvm
# https://github.com/moovweb/gvm/blob/master/binscripts/gvm-installer
- name: Create directories
  file:
    dest: "{{ gvm_root | dirname }}"
    state: directory
- name: Clone gvm
  git:
    repo: "{{ gvm_repo }}"
    dest: "{{ gvm_root }}"
    version: "{{ gvm_version }}"
    update: "{{ gvm_update }}"
- block:
  - name: Add configurations to ~/.bashrc, ~/.profile, or ~/.zshrc or etc
    lineinfile:
      dest: "{{ gvm_rc_path }}"
      line: 'export GVM_ROOT="{{ gvm_root }}"'
      regexp: '^export GVM_ROOT='
      create: yes
  - name: Add configurations to ~/.bashrc, ~/.profile, or ~/.zshrc or etc
    lineinfile:
      dest: "{{ gvm_rc_path }}"
      line: '. $GVM_ROOT/scripts/gvm-default'
      create: yes
  when: gvm_rc_path != "NOT ADD"
- include: "{{ gvm_os_families.get(ansible_os_family, 'default') }}.yml"
  static: no
  when: gvm_is_dependencies_installed and ansible_os_family in gvm_os_families
