---
name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install molecule
        run: |
          pip install --upgrade pip
          pip install "molecule[docker,lint]"
      - name: test
        run: molecule test
